name: Run tests

on: [push, pull_request]

defaults:
  run:
    shell: bash


jobs:
  specs:
    name: 'run-specs'
    # skip on [ci skip] and do not run 2 on push and interal PR
    if: (contains(github.event.commits[0].message, '[ci skip]') == false) &&  (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    continue-on-error: ${{ matrix.allow_failure || false }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true

      - name: run specs
        run: |
          bundle exec rake

      # needs the right code climate reporter id
      # - name: Test & publish code coverage
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: <code_climate_reporter_id>
